* nebula

** requirements
*** [[https://github.com/ggerganov/llama.cpp][llama.cpp]] backend
**** CPU
***** Windows
- [[https://github.com/skeeto/w64devkit/releases][w64devkit]]
  - Download the latest fortran version of [[https://github.com/skeeto/w64devkit/releases][w64devkit]].
  - Extract w64devkit.
  - Run ~w64devkit.exe~
**** Acceleration
***** CPU openBLAS
This provides BLAS acceleration using only the CPU.
-  Windows
  -  [[https://github.com/skeeto/w64devkit/releases][w64devkit]]
    - Download the latest fortran version of [[https://github.com/skeeto/w64devkit/releases][w64devkit]].
    - Download the latest version of [[https://github.com/xianyi/OpenBLAS/releases][OpenBLAS for Windows]].
    - Extract w64devkit.
    - From the OpenBLAS zip that you just downloaded copy ~libopenblas.a~, located inside the ~lib~ folder, inside ~w64devkit\x86_64-w64-mingw32\lib~.
    - From the same OpenBLAS zip copy the content of the ~include~ folder inside ~w64devkit\x86_64-w64-mingw32\include~.
    - Run ~w64devkit.exe~.
***** NVIDIA GPU
This provides BLAS acceleration using the CUDA cores of your Nvidia
GPU
- Windows, Linux
  - [[https://developer.nvidia.com/cuda-downloads][Cuda Toolkit]]
***** AMD GPU
This provides BLAS acceleration on HIP-supported AMD GPUs.
- Windows, Linux
  -  [[https://rocm.docs.amd.com/en/latest/deploy/linux/quick_start.html][ROCm]]

***** Intel GPU
The llama.cpp SYCL backend is designed to support Intel GPU. Based on
the cross-platform feature of SYCL, it could support other vendor
GPUs: Nvidia GPU (AMD GPU coming).
When targeting Intel CPU, it is recommended to use Intel oneMKL
backend.

- Linux, Windows
  - Install GPU drivers

    Intel data center GPUs drivers installation guide and download
    page can be found here: [[https://dgpu-docs.intel.com/driver/installation.html#ubuntu-install-steps][Get intel dGPU
    Drivers]]
    For client GPUs (iGPU & Arc A-Series), please refer to the client
    [[https://dgpu-docs.intel.com/driver/client/overview.html][iGPU
    driver installation]].

  - The base toolkit can be obtained from the official
    [[https://www.intel.com/content/www/us/en/developer/tools/oneapi/base-toolkit.html#gs.8i8gub][Intel®
    oneAPI Base Toolkit page]].



* [[https://github.com/nchapman/nebula/tree/main/examples][examples]]
